# HIERARCHICAL INDEXING HAV LEVEL IT SUPPORTS FOR 4D IN UPCOMING VERSIONS PANDAS 4D IS ELIMINATED ONLY 2D WILL BE GENERATED

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [7]:
pd. __version__

'0.25.3'

In [8]:
np.__version__

'1.18.1'

In [9]:
sns.__version__

'0.9.0'

In [10]:
plt.__version__

AttributeError: module 'matplotlib.pyplot' has no attribute '__version__'

In [11]:
ind = [('california',2000),('california',2010),
      ('New york',2000),('New york',2010),
       ('Texas',2000),('Texas',2010)]
populations = [33871648, 37253956,
              18946457, 19378102,
              20851820, 25145561]

In [12]:
pop = pd.Series(populations,index=ind)
pop

(california, 2000)    33871648
(california, 2010)    37253956
(New york, 2000)      18946457
(New york, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [13]:
pop[0]

33871648

In [16]:
pop[0:4]

(california, 2000)    33871648
(california, 2010)    37253956
(New york, 2000)      18946457
(New york, 2010)      19378102
dtype: int64

In [20]:
pop[[i for i in pop.index if i[1] == 2010]]  # usimg list comprehension

(california, 2010)    37253956
(New york, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [18]:
for i in pop.index:
    if i[1] == 2010:
        print(i,pop[i])

('california', 2010) 37253956
('New york', 2010) 19378102
('Texas', 2010) 25145561


In [21]:
pop.index

Index([('california', 2000), ('california', 2010),   ('New york', 2000),
         ('New york', 2010),      ('Texas', 2000),      ('Texas', 2010)],
      dtype='object')

In [22]:
index = pd.MultiIndex.from_tuples(ind)
index

MultiIndex([('california', 2000),
            ('california', 2010),
            (  'New york', 2000),
            (  'New york', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [23]:
pop = pop.reindex(index)   # here default index is deleted in memory 
pop

california  2000    33871648
            2010    37253956
New york    2000    18946457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [24]:
pop["california"]

2000    33871648
2010    37253956
dtype: int64

In [27]:
pop['New york'][2010]

19378102

In [29]:
pop[0:3]

california  2000    33871648
            2010    37253956
New york    2000    18946457
dtype: int64

In [30]:
pop[0:4]

california  2000    33871648
            2010    37253956
New york    2000    18946457
            2010    19378102
dtype: int64

In [31]:
pop[0::2]

california  2000    33871648
New york    2000    18946457
Texas       2000    20851820
dtype: int64

In [40]:
pop_df = pop.unstack()
pop_df

2000      2010
New york    18946457  19378102
Texas       20851820  25145561
california  33871648  37253956

In [41]:
pop_df.ndim

2

In [42]:
se=pop_df.stack()
se

New york    2000    18946457
            2010    19378102
Texas       2000    20851820
            2010    25145561
california  2000    33871648
            2010    37253956
dtype: int64

In [43]:
# HERE STACK AND UNSTACK IS AS FLATTEN() AND RAVEL 
# HERE STACK IS 

In [45]:
pop_df = pd.DataFrame({'Total':pop,
                      'under18':[9267089, 9284094,
                                 4687374, 4318033,
                                 5906301, 6879014]})
pop_df

Total  under18
california 2000  33871648  9267089
           2010  37253956  9284094
New york   2000  18946457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [46]:
pop_df['Total']

california  2000    33871648
            2010    37253956
New york    2000    18946457
            2010    19378102
Texas       2000    20851820
            2010    25145561
Name: Total, dtype: int64

In [48]:
f_u18 = pop_df['under18'] / pop_df['Total']
f_u18.unstack()

2000      2010
New york    0.247401  0.222831
Texas       0.283251  0.273568
california  0.273594  0.249211

# METHODS OF MULTI INDEX

In [49]:
df = pd.DataFrame(np.random.rand(4,2),
                 index=[['a','a','b','b'],[1,2,1,2]],
                 columns=['data1','data2'])
df

data1     data2
a 1  0.140440  0.143248
  2  0.717126  0.245729
b 1  0.745547  0.522377
  2  0.096671  0.834206

In [52]:
df = pd.DataFrame(np.random.rand(4,2),
                 index=[['a','b','a','b'],[1,2,1,2]],
                 columns=['data1','data2'])
df

data1     data2
a 1  0.825378  0.293032
b 2  0.116030  0.390872
a 1  0.889390  0.124264
b 2  0.282786  0.875900

In [53]:
data = {('california',2000): 33871648,
       ('california',2010): 37253956,
       ('texas',2000): 20851820,
       ('texas',2010): 25145561,
       ('newyork',2000): 18976457,
       ('newyork',2010): 19378102}
pd.Series(data)

california  2000    33871648
            2010    37253956
texas       2000    20851820
            2010    25145561
newyork     2000    18976457
            2010    19378102
dtype: int64

In [54]:
pd.MultiIndex.from_arrays([['a','a','b','b'], [1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [55]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [56]:
pd.MultiIndex.from_product([['a','b'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [57]:
pd.MultiIndex(levels=[['a','b'],[1,2]],
             codes=[[0,0,1,1],[0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [58]:
pop.index.names= ['state','year']
pop

state       year
california  2000    33871648
            2010    37253956
New york    2000    18946457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [59]:
index = pd.MultiIndex.from_product([[2013,2014],[1,2,3]],
                                  names=['year','visit'])
columns = pd.MultiIndex.from_product([['rani','raju','sam'],['bmi','temp','weight']],
                                    names = ['name','type'])

In [61]:
data = np.round(np.random.randn(6,9),2)
data

array([[-1.65, -0.27, -0.02,  1.4 , -0.2 ,  2.25, -0.33, -1.1 ,  0.46],
       [-1.78,  0.13, -1.73,  0.94,  0.01,  1.59, -1.68, -0.95, -0.98],
       [-0.73,  0.15,  0.02, -0.9 , -1.5 ,  1.21, -0.39, -1.55, -1.89],
       [-1.31,  0.56,  0.97, -0.49,  0.62, -0.09, -1.1 , -0.29, -1.02],
       [ 0.95, -1.51,  0.44, -1.12,  0.64, -0.26, -2.24,  1.27, -1.44],
       [-0.75,  0.69, -0.65, -0.6 , -0.5 ,  1.19, -0.26, -2.02, -0.15]])

In [64]:
data[:,::2]*10

array([[-16.5,  -0.2,  -2. ,  -3.3,   4.6],
       [-17.8, -17.3,   0.1, -16.8,  -9.8],
       [ -7.3,   0.2, -15. ,  -3.9, -18.9],
       [-13.1,   9.7,   6.2, -11. , -10.2],
       [  9.5,   4.4,   6.4, -22.4, -14.4],
       [ -7.5,  -6.5,  -5. ,  -2.6,  -1.5]])

In [66]:
data+=37
data

array([[72.35, 73.73, 73.98, 75.4 , 73.8 , 76.25, 73.67, 72.9 , 74.46],
       [72.22, 74.13, 72.27, 74.94, 74.01, 75.59, 72.32, 73.05, 73.02],
       [73.27, 74.15, 74.02, 73.1 , 72.5 , 75.21, 73.61, 72.45, 72.11],
       [72.69, 74.56, 74.97, 73.51, 74.62, 73.91, 72.9 , 73.71, 72.98],
       [74.95, 72.49, 74.44, 72.88, 74.64, 73.74, 71.76, 75.27, 72.56],
       [73.25, 74.69, 73.35, 73.4 , 73.5 , 75.19, 73.74, 71.98, 73.85]])

In [67]:
health_data=pd.DataFrame(data, index=index,columns=columns)
health_data

name         rani                 raju                  sam              
type          bmi   temp weight    bmi   temp weight    bmi   temp weight
year visit                                                               
2013 1      72.35  73.73  73.98  75.40  73.80  76.25  73.67  72.90  74.46
     2      72.22  74.13  72.27  74.94  74.01  75.59  72.32  73.05  73.02
     3      73.27  74.15  74.02  73.10  72.50  75.21  73.61  72.45  72.11
2014 1      72.69  74.56  74.97  73.51  74.62  73.91  72.90  73.71  72.98
     2      74.95  72.49  74.44  72.88  74.64  73.74  71.76  75.27  72.56
     3      73.25  74.69  73.35  73.40  73.50  75.19  73.74  71.98  73.85

In [68]:
health_data.to_csv("health_data.csv")

In [69]:
health_data['rani']

type          bmi   temp  weight
year visit                      
2013 1      72.35  73.73   73.98
     2      72.22  74.13   72.27
     3      73.27  74.15   74.02
2014 1      72.69  74.56   74.97
     2      74.95  72.49   74.44
     3      73.25  74.69   73.35

In [72]:
health_data.iloc[1]  # here iloc means integer lock or index lock

name  type  
rani  bmi       72.22
      temp      74.13
      weight    72.27
raju  bmi       74.94
      temp      74.01
      weight    75.59
sam   bmi       72.32
      temp      73.05
      weight    73.02
Name: (2013, 2), dtype: float64

In [79]:
health_data.iloc[::]

name         rani                 raju                  sam              
type          bmi   temp weight    bmi   temp weight    bmi   temp weight
year visit                                                               
2013 1      72.35  73.73  73.98  75.40  73.80  76.25  73.67  72.90  74.46
     2      72.22  74.13  72.27  74.94  74.01  75.59  72.32  73.05  73.02
     3      73.27  74.15  74.02  73.10  72.50  75.21  73.61  72.45  72.11
2014 1      72.69  74.56  74.97  73.51  74.62  73.91  72.90  73.71  72.98
     2      74.95  72.49  74.44  72.88  74.64  73.74  71.76  75.27  72.56
     3      73.25  74.69  73.35  73.40  73.50  75.19  73.74  71.98  73.85